/*  SOBRE A IDE
    ==============================================================================================
    Gerado pela IDE Designer
    1.0.22.0 RELEASE CANDIDATE (RC) 220301 1913
    https://github.com/ivanilmarcelino/designer by IVANIL MARCELINO <ivanil.marcelino@yahoo.com.br>
    Versão Minigui:  Harbour MiniGUI Extended Edition 22.01.4 (32-bit) ANSI  Grigory Filatov <gfilatov@inbox.ru>
    Versão Harbour/xHarbour: Harbour 3.2.0dev (r2104281802)
    Compilador : MinGW GNU C 11.2 (32-bit)
    ----------------------------------------------------------------------------------------------
    SOBRE ESTE CÓDIGO GERADO:
    Última alteração : 03/03/2022-22:06:56 Máquina: IMA2018 Usuário:Ivanil
    Código Módulo Main
    ----------------------------------------------------------------------------------------------
    Projeto : Nogui
    */

Function Main( )
    Local i
    #Include <Nogui.CH>
    For i=1 to 1000
        ?i,"Ola Mundo"
    next
    inkey(0)
    REturn .T.
